export const buttonPlay = document.querySelector(".play")
export const buttonPause = document.querySelector(".pause")
export const buttonStop = document.querySelector(".stop")
export const buttonSet = document.querySelector(".set")
export const buttonSoundOn = document.querySelector(".sound-on")
export const buttonSoundOff = document.querySelector(".sound-off")
export const minutesDisplay = document.querySelector(".minutes")
export const secondsDisplay = document.querySelector(".seconds")
